apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: deploy-dog
  name: deploy-dog
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-dog
  template:
    metadata:
      labels:
        app: deploy-dog
    spec:
      containers:
      - image: ddocker122/dog_breed:latest
        imagePullPolicy: Always
        name: deploy-dog
        ports:
        - containerPort: 5000
        # resources:
        #   limits:
        #     cpu: 600.0m
      terminationGracePeriodSeconds: 2
