apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: default
spec:
  selector:
    app: node-exporter
  type: NodePort
  externalIPs:
    - 192.168.20.8
  ports:
    - name: http
      protocol: TCP
      port: 9100
      targetPort: 9100
