apiVersion: v1
kind: Service
metadata:
  name: service-cat
  namespace: default
spec:
  clusterIP: 10.96.10.40
  type: NodePort
  selector:
    app: deploy-cat
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30995
