apiVersion: v1
kind: Service
metadata:
  name: service-dog
  namespace: default
spec:
  clusterIP: 10.96.10.50
  type: NodePort
  selector:
    app: deploy-dog
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30994
