apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: default
spec:
  clusterIP: 10.96.10.10
  type: NodePort
  selector:
    app: deploy-a
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30999
