apiVersion: v1
kind: Service
metadata:
  name: service-binary
  namespace: default
spec:
  clusterIP: 10.96.10.30
  type: NodePort
  selector:
    app: deploy-binary-cat-dog
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30996
