apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: default
spec:
  clusterIP: 10.96.10.20
  type: NodePort
  selector:
    app: deploy-b
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30998
